// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2QhZlOyNO0tGcfWgGH0QnjTHuLo7URkA',
    appId: '1:1051779189687:web:310a3565dda40599c53632',
    messagingSenderId: '1051779189687',
    projectId: 'nzxtgen-app',
    authDomain: 'nzxtgen-app.firebaseapp.com',
    storageBucket: 'nzxtgen-app.firebasestorage.app',
    measurementId: 'G-C207B7KBWP',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcAYEBfTsxcC8hH_B8HpynZmxRl8E27ck',
    appId: '1:1051779189687:ios:a8aa31a8606a6d03c53632',
    messagingSenderId: '1051779189687',
    projectId: 'nzxtgen-app',
    storageBucket: 'nzxtgen-app.firebasestorage.app',
    iosClientId: '1051779189687-q9kaki0ctliq2opcfqil1fh0nsqn4hut.apps.googleusercontent.com',
    iosBundleId: 'com.example.nzxtgenOs',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcAYEBfTsxcC8hH_B8HpynZmxRl8E27ck',
    appId: '1:1051779189687:ios:a8aa31a8606a6d03c53632',
    messagingSenderId: '1051779189687',
    projectId: 'nzxtgen-app',
    storageBucket: 'nzxtgen-app.firebasestorage.app',
    iosClientId: '1051779189687-q9kaki0ctliq2opcfqil1fh0nsqn4hut.apps.googleusercontent.com',
    iosBundleId: 'com.example.nzxtgenOs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2QhZlOyNO0tGcfWgGH0QnjTHuLo7URkA',
    appId: '1:1051779189687:web:5e1d87512987a37dc53632',
    messagingSenderId: '1051779189687',
    projectId: 'nzxtgen-app',
    authDomain: 'nzxtgen-app.firebaseapp.com',
    storageBucket: 'nzxtgen-app.firebasestorage.app',
    measurementId: 'G-FKB8TCWRT7',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_-G0LyQzcrTxrL7VpqGofMe4zuhg_9-Y',
    appId: '1:1051779189687:android:6edcbc7bcd7f1a86c53632',
    messagingSenderId: '1051779189687',
    projectId: 'nzxtgen-app',
    storageBucket: 'nzxtgen-app.firebasestorage.app',
  );
}
